import oracledb as PBD

def dbConectar():
    ip = "localhost"
    puerto = 1521
    s_id = "xe"

    usuario = "system"
    contrasena = "12345"

    print("---dbConectar---")
    print("---Conectando a Oracle---")

    try:
        conexion = PBD.connect(user=usuario, password=contrasena, host=ip, port=puerto, sid=s_id)
        print("Conexión realizada a la base de datos",conexion)
        return conexion
    except PBD.DatabaseError as error:
        print("Error en la conexión")
        print(error)
        return None

#----------------------------------------------------

def dbDesconectar():
    print("---dbDesconectar---")
    try:
        conexion.close()
        print("Desconexión realizada correctamente")
        return True
    except PBD.DatabaseError as error:
        print("Error en la desconexión")
        print(error)
        return False

#-----------------------------------------------------------

def configuracionTablas(conexion):
    print("---configuracionTablas---")
    try:
        cursor = conexion.cursor()
        consulta=("""
            CREATE TABLE Usuarios (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL,
                password VARCHAR2(50) NOT NULL
            )
        """)
        cursor.execute(consulta)
        cursor.close()


        cursor.execute(consulta)
        cursor.close()

        cursor = conexion.cursor()
        consulta=("""SELECT * FROM Usuarios""")
        cursor.execute(consulta)
        cursor.close()
        print("Tabla 'usuarios' creada exitosamente")
        return True
    except PBD.DatabaseError as error:
        print("Error al crear la tabla")
        print(error)
        return False

#--------------------------------------------------------------

conexion = dbConectar()

if conexion:
    configuracionTablas(conexion)

    dbDesconectar()